### ISSUE TITLE
Get the name of the invalid property

### ISSUE THREAD

**Issue by Aaronmacaron** [lezhnev74/openapi-psr7-validator#50] opened 2019-08-10 13:54 UTC
I'm trying to use this library to generate error messages that are visible to the end-user. Thus I need a way to find out the name of the property that's not valid.

As far as I can tell there is no way to this right now. I'm thinking of something like that:

```php
try {
 // Validation
} catch (OpenAPIValidation\PSR7\Exception\Validation\InvalidBody $e) {
    $property = $e->getInvalidPropertyName();
    echo "The field '$property' is not valid. Please correct it and try again."
}
```

Is something like that possible and if not are there any plans to implement this?

Thanks

**Comment by scaytrase** [comment] 2019-08-10 14:03
Invalid body could be caused by different reasons. `SchemaMismatch` is one of them. You can try to inspect previous exception in order to find out the real reason

**Comment by Aaronmacaron** [comment] 2019-08-14 09:00
Unfortunately none of the previous Exceptions such as `SchemaMismatch` contain the name of the property that is not valid. Thanks anyway.

**Comment by scaytrase** [comment] 2019-08-14 09:04
`SchemaMismatch` contains breadcrumbs which could be converted to path

https://github.com/lezhnev74/openapi-psr7-validator/blob/6811d29e145638f2e9271c1ec0e721a40a23f745/src/Schema/Exception/SchemaMismatch.php#L19

**Comment by Aaronmacaron** [comment] 2019-08-24 15:56
In my case the BreadCrumb is unfortunately emtpy (`compoundIndex` and `prevCrumb` are null)

**Comment by scaytrase** [comment] 2019-08-24 16:22
hm, this sounds like a potential bug. can provide a simple test case that reproduces this issue? If yes we can try fix it

**Comment by Aaronmacaron** [comment] 2019-09-11 14:51
Okay I think I know what the problem is. 

Suppose you have a schema that requires a JSON object like this:

```JSON
{
  "username": "Foo",
  "email": "bar@foobar.com"
}
```

Now, when the client submits following JSON the "Required" validator fails because the `email` property is missing.

```JSON
{
  "username": "Foo",
  "notEmail": "bar@foobar.com"
}
```

The dataBreadCrumb is null because the `SchemaValidator` is validating the toplevel JSON object and not the `email` property.

I'm aware that is not a bug Per se. Nevertheless it would be very useful if there was a way to obtain the name of the missing field in the Exception.

**Comment by scaytrase** [comment] 2019-09-11 15:32
great, I think we can fix this having this info for sure

ср, 11 сент. 2019 г., 17:51 Aaron Ebnöther <notifications@github.com>:

**Comment by coatesap** [comment] 2019-09-26 11:52
For anyone looking to extract the reason for the failure (under normal conditions), this worked for me:
```php
} catch (\OpenAPIValidation\PSR7\Exception\Validation\InvalidBody $exception) {
    return $exception->getPrevious()->getMessage();
}
// Will return something like:
// "Value '2019-09-01 12:12:12' does not match format date-time of type string"
```

**Comment by scaytrase** [comment] 2019-09-27 07:23
Moved this into https://github.com/thephpleague/openapi-psr7-validator/issues/14

**Comment by scaytrase** [comment] 2020-05-16 15:04
Created https://github.com/thephpleague/openapi-psr7-validator/pull/57/files to address this

**Comment by scaytrase** [comment] 2020-05-16 16:55
@lezhnev74 this one is fixed in the mainstream, may be closed

**Closed as completed** 2020-05-17 07:14 UTC
