### ISSUE TITLE
Issues using readFromYamlFile() on Windows

### ISSUE THREAD

**Issue by brayniverse** [lezhnev74/openapi-psr7-validator#9] opened 2019-05-09 07:19 UTC
There is an issue with the underlying `cebe/php-openapi` library for Windows users that prevents us from calling `readFromYamlFile()`. @scaytrase has [opened an issue on their repo](https://github.com/cebe/php-openapi/issues/22) so hopefully it'll be fixed soon. However, this bug is fixed in the underlying library the examples in the README file will not work as described for Windows users.

In order to read the YAML file I had to do something slightly different to the example:

```php
$yamlFile = "api.yaml";

$validator = new \OpenAPIValidation\PSR7\ResponseValidator(
    \cebe\openapi\Reader::readFromYaml(file_get_contents($yamlFile))
);

$operation = new \OpenAPIValidation\PSR7\OperationAddress('/password/gen', 'get') ;

$validator->validate($operation, $request);
```

Would you like me to submit a PR to update the README examples to use `file_get_contents()` as a temporary solution?

---

I have also found that I am unable to run the test suite for the same reason. For reference, this is the error I get:

> OpenAPIValidationTests\PSR7\CompleteTest::test_request_green
cebe\openapi\exceptions\UnresolvableReferenceException: Can not resolve references for a specification given as a relative path.

I tried updating the failing test to use `file_get_contents()` but I get another error:

> OpenAPIValidationTests\PSR7\CompleteTest::test_request_green
OpenAPIValidation\PSR7\Exception\Request\RequestBodyMismatch: OpenAPI spec does not match the body of the request [/complete/{param1}/{param2},post]: Argument 1 passed to OpenAPIValidation\Schema\Validator::__construct() must be an instance of cebe\openapi\spec\Schema, instance of cebe\openapi\spec\Reference given

I'll have a crack at getting the test suite to run but I thought I'd bring this up in case it's affecting anyone else.

**Comment by brayniverse** [comment] 2019-05-09 07:20
I just checked the `cebe/php-openapi` issue I referenced and they've acknowledged the problem.

**Comment by scaytrase** [comment] 2019-05-09 07:25
> I tried updating the failing test to use file_get_contents() but I get another error:

In order to use references you should resolve them manually beforehand, see #4

**Comment by lezhnev74** [comment] 2019-05-09 07:26
@brayniverse very good catch! 

> Would you like me to submit a PR to update the README examples to use file_get_contents() as a temporary solution?

I'd love it if you could add a note for Windows Users (with a reference to a causing bug report).

**Comment by lezhnev74** [comment] 2019-05-09 07:29
I've added a paragraph to Readme file about this references issue.

**Comment by brayniverse** [comment] 2019-05-09 08:08
> 
> 
> @brayniverse very good catch!
> 
> > Would you like me to submit a PR to update the README examples to use file_get_contents() as a temporary solution?
> 
> I'd love it if you could add a note for Windows Users (with a reference to a causing bug report).

I've submitted a pull request (#10) but I think there's another issue with `ValidationMiddleware` because it's [`readOAS()` method calls `readFromYamlFile()`](https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR15/ValidationMiddleware.php#L86).

**Comment by scaytrase** [comment] 2019-05-09 08:11
Looks like it is a good idea do decouple spec retrieval method from middleware. not every spec is even stored in a file. I can submit separate issue about this if you want (we do not use these middlewares at the moment)

**Comment by lezhnev74** [comment] 2019-05-09 09:39
Nah, let's keep it here for now. 

> Looks like it is a good idea do decouple spec retrieval method from middleware.

Good point. I'll extract it. Should be quite straightforward.

**Comment by lezhnev74** [comment] 2019-05-09 09:44
Ok, `0.9.0` contains the fix

**Comment by lezhnev74** [comment] 2019-05-09 10:51
Pushed `0.10.0` which does auto-resolving of dependencies

**Comment by brayniverse** [comment] 2019-05-09 12:17
Ran the test suite with new auto-resolving feature (and changing `fromYamlFile` to `fromYaml`) but I get this exception on Windows now.

>OpenAPIValidationTests\PSR7\CompleteTest::test_request_green
cebe\openapi\exceptions\UnresolvableReferenceException: Failed to resolve Reference 'schemas.yaml#/components/schemas/SchemaA' to ce
be\openapi\spec\Schema Object: file_get_contents(./schemas.yaml): failed to open stream: No such file or directory

**Comment by lezhnev74** [comment] 2019-05-09 12:21
Looks like I am missing something about Windows... Let me check again.

**Comment by lezhnev74** [comment] 2019-05-09 12:33
I am setting up a virtual box with Windows installed and gonna see what causes this.

**Comment by brayniverse** [comment] 2019-05-09 12:42
Thank you.

**Comment by lezhnev74** [comment] 2019-05-09 13:28
@brayniverse can you extend your input:
- did you run standard tests suit `./vendor/bin/phpunit`?
- if you run your own test, can you provide full text for both file content and code?

**Comment by lezhnev74** [comment] 2019-05-09 14:01
Ok, confirmed. It does not work on windows out of the box:

![image](https://user-images.githubusercontent.com/10206110/57459503-cd7cb200-728c-11e9-969f-9e7bfc9d03fd.png)

It looks like the root (as you mentioned) is here: https://github.com/cebe/php-openapi/issues/22

**Comment by brayniverse** [comment] 2019-05-09 14:05
@lezhnev74 I ran `./vendor/bin/phpunit` without any modifications and got this error:

> 1) OpenAPIValidationTests\PSR7\CompleteTest::test_request_green
cebe\openapi\exceptions\UnresolvableReferenceException: Can not resolve references for a specification given as a relative path.

I updated CompleteTest::test_request_green like so:

```diff
<?php
/**
 * @author Dmitry Lezhnev <lezhnev.work@gmail.com>
 * Date: 06 May 2019
 */
declare(strict_types=1);


namespace OpenAPIValidationTests\PSR7;


use cebe\openapi\Reader;
use GuzzleHttp\Psr7\Response;
use GuzzleHttp\Psr7\ServerRequest;
use OpenAPIValidation\PSR7\OperationAddress;
use OpenAPIValidation\PSR7\ResponseValidator;
use OpenAPIValidation\PSR7\ServerRequestValidator;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use function GuzzleHttp\Psr7\stream_for;

// This is another test which tests all request and response with variety of specified parameters:
// - path,
// - query arguments,
// - cookie,
// - request header,
// - request body,
// - response header
// - response body
class CompleteTest extends TestCase
{
    protected $apiSpecFile = __DIR__ . "/../stubs/complete.yaml";

    protected function buildGoodRequest(): ServerRequestInterface
    {
        return (new ServerRequest("post", "/complete/good/2"))
            ->withQueryParams(['limit'=>10, 'filtering'=>'good'])
            ->withCookieParams(['session_id' => 100])
            ->withHeader('X-RequestId', 'abcd')
            ->withHeader('Content-Type', 'application/json')
            ->withBody(stream_for(json_encode(['propB' => 'good value'])));
    }

    protected function buildGoodResponse(): ResponseInterface
    {
        return (new Response())
            ->withHeader('Content-Type', 'application/json')
            ->withBody(stream_for(json_encode(['propA' => PHP_INT_MAX])));
    }


    function test_request_green()
    {
        $request = $this->buildGoodRequest();

-        $validator = ServerRequestValidator::fromYamlFile($this->apiSpecFile);
+        $validator = ServerRequestValidator::fromYaml(file_get_contents($this->apiSpecFile));
        $validator->validate($request);
        $this->addToAssertionCount(1);
    }

    function test_response_green()
    {
        $response = $this->buildGoodResponse();
        $addr = new OperationAddress("/complete/{param1}/{param2}", "post");

        $validator = ResponseValidator::fromYamlFile($this->apiSpecFile);
        $validator->validate($addr, $response);
        $this->addToAssertionCount(1);
    }

}
```

and get the following error:
> 1) OpenAPIValidationTests\PSR7\CompleteTest::test_request_green
cebe\openapi\exceptions\UnresolvableReferenceException: Failed to resolve Reference 'schemas.yaml#/components/schemas/SchemaA' to ce
be\openapi\spec\Schema Object: file_get_contents(./schemas.yaml): failed to open stream: No such file or directory

I hope that helps.

**Comment by brayniverse** [comment] 2019-05-09 14:06
> 
> 
> Ok, confirmed. It does not work on windows out of the box:
> 
> ![image](https://user-images.githubusercontent.com/10206110/57459503-cd7cb200-728c-11e9-969f-9e7bfc9d03fd.png)
> 
> It looks like the root (as you mentioned) is here: [cebe/php-openapi#22](https://github.com/cebe/php-openapi/issues/22)

Nice. Thanks for looking into it. Let me know if there is anything I can do to help.

**Comment by scaytrase** [comment] 2019-05-16 09:11
I've created quickfix for it

https://github.com/cebe/php-openapi/pull/25

I hope this could be closed, as there is nothing could be done on this lib side

**Comment by lezhnev74** [comment] 2019-05-16 12:27
Well, let's close it as soon as the underlying package fixes it, just to avoid duplicates from other developers.

**Comment by cebe** [comment] 2019-05-20 15:20
I just released version 1.0.1 of cebe/php-openapi, which fixes cebe/php-openapi#22 and other windows related issues. Also added travis-ci tests for windows environment.

https://github.com/cebe/php-openapi/releases/tag/1.0.1

**Comment by lezhnev74** [comment] 2019-05-20 15:25
Cool! My windows setup shows green:
![image](https://user-images.githubusercontent.com/10206110/58033149-6341f800-7b3d-11e9-899a-cfb4e96cef77.png)

@brayniverse check the last version

**Comment by scaytrase** [comment] 2019-05-21 06:27
Yeah, test ran without additional hacks.

**Closed as completed** 2019-05-21 06:28 UTC
Labels: bug

**Comment by brayniverse** [comment] 2019-05-21 08:07
I get a few different errors now, seeing as they pass for you it's probably something I've done. I'll pull everything down fresh this afternoon and give it another try. Thanks @lezhnev74 @scaytrase

**Comment by lezhnev74** [comment] 2019-05-21 08:35
Sure, keep us posted here.
